In [93]:
import pandas as pd
import datetime
import numpy as np
import re
import seaborn as sns

In [2]:
df = pd.read_csv("cleaned_survey_results_2019.csv")

In [3]:
len(df)

1359

In [4]:
df = df.reset_index()

In [5]:
for i in df.columns:
    print(i)

index
Have you studied data visualization in school (or other formal environment) or did you learn how to do it on your own?
What methods do you think best teach data visualization?
What area is your next priority for improving your data visualization skills?
Are you a freelancer/consultant?
What focus is data visualization in your work?
For the majority of your projects: were you hired to do data visualization only or is data visualization a part of your job/project description?
Do you do more or less data visualization than you expected for this role?
Which one of these is the closest to describing your role?
What is your yearly pay?
What is your hourly rate?
How is your organization using data visualization? Select all that apply.
Is there a separate group dedicated to creating data visualization or are data visualization specialists embedded in another group? (data science, UX, UI, web, data engineering, IT, etc)
What modes of data visualization are in use at your organization? Select all that apply.
Leadership in your organization has a strong understanding of the value of data visualization.
Data visualization at your organization features prominently in what parts of the organization? Select all that apply.
Hours a week focused on creating/implementing/productizing data visualizations?
Hours a week focused on data engineering?
Hours a week focused on data science?
Hours a week focused on design?
Hours a week focused on data prep work?
Hours a week focused on building your portfolio?
What technologies do you use to visualize data? Select all that apply.
Are you able to choose your own tools or are the choices made for you?
How do you present your data visualizations? Select all that apply.
Which of these charts have you used in production in the last 6 months? Select all that apply.
Who do you make data visualizations for? Select all that apply.
What knowledge level does your audience have of the data you are visualizing for them? Select all that apply.
Most typically, how often does your audience use your data visualization?
What does your audience use your data visualization for? Select all that apply.
How would you describe your relationship with stakeholders?
I have adequate resources to explore the data visualization options I want to use.
What is your biggest frustration with doing data visualization in your job?
If you could change one thing about your data visualization work what would it be?
What do you think other people in your organization just don’t get about the data visualization work that you do?
I want to make better visualizations but don’t have the time/energy/resources.
I’m always on the lookout for new data visualization tools and techniques that will make my workflows faster and more efficient.
My skills hold me back much more than my tools do.
What one change would make the data visualization aspect of your job better?
What community support / discussions / advice would you want to see from data visualization thought leaders?
Who do you look to as a thought leader in data visualization?
Do you want to spend more time or less time visualizing data in the future?
How many years of experience do you have doing professional data visualization?
What is your educational background
The organization you work for is in which of the following areas?
If you went to college, what did you major in during your undergraduate work?
What's your gender identity?
Do you consider yourself a member of the LGBTQ+ community?
What city do you live in?
What country do you live in?
What non-programming languages do you use regularly?

In [38]:
df = df.rename(columns={'What country do you live in?': 'country', \
'How many years of experience do you have doing professional data visualization?': 'years',\
'Which one of these is the closest to describing your role?': 'role', \
'What focus is data visualization in your work?': 'level', \
'What modes of data visualization are in use at your organization? Select all that apply.': 'mode',\
'Leadership in your organization has a strong understanding of the value of data visualization.': "value",
'For the majority of your projects: were you hired to do data visualization only or is data visualization a part of your job/project description?': "vizfocus"
})

In [70]:
df_level = pd.DataFrame(df.groupby(['country','level'])['index'].size())
df_level = df_level.groupby(level=0).apply(lambda x: 100 * x / float(x.sum()))\
.reset_index().rename(columns={'index': 'perc'})
df_level = df_level[df_level['level'] == 'Data visualization is the focus of my job']
df_level.to_csv('grouped_level.csv', index=False)

In [7]:
df['level'].unique()

array(['Data visualization is an important secondary part of my job, but not the focus',
       'Data visualization is the focus of my job',
       'Data visualization is one of several other things I do in my job, but not a primary or secondary part of my role',
       nan], dtype=object)

In [8]:
df['role'].unique()

array(['Academic', 'Leadership (Manager, Director, VP, etc)', 'Developer',
       'Analyst', 'None of these describe my role', 'Student', 'Engineer',
       'Designer', 'Scientist', 'Freelancer'], dtype=object)

In [9]:
df['role'] = df['role'].replace('Freelancer', 'None of these describe my role')

In [10]:
df['country'].unique()

array(['USA', 'Tanzania', 'Greece', 'Australia', 'Vietnam', 'Spain',
       'Canada', nan, 'El Salvador', 'United Kingdom', 'Chile', 'Sweden',
       'India', 'England', 'Argentina', 'France', 'Luxembourg', 'Germany',
       'Italy', 'Peru', 'Japan', 'Mexico', 'Brazil', 'South Africa',
       'Ireland', 'Europe', 'Singapore', 'Belgium', 'Hong Kong ',
       'Malaysia', 'New Zealand', 'Russia', 'Hungary', 'Finland',
       'Turkey', 'Denmark', 'Netherlands', 'Estonia', 'Switzerland',
       'Colombia', 'Usa', 'Kenya', 'Tunisia', 'Germany ', 'England ',
       'Kuwait', 'Slovenia', 'Uganda', 'Dominican Republic', 'Indonesia',
       'Serbia', 'Scotland', 'Hong Kong', 'Finland ', 'Ecuador',
       'Costa Rica', 'Iceland', 'United Kingdom ', 'Russia ',
       'Saudi Arabia', 'Norway', 'Poland', 'Austria', 'India ', 'Cuba',
       'Lebanon', 'Portugal', 'South Africa ', 'Croatia', 'Belarus',
       'Georgia', 'Bermuda', 'Romania', 'Uruguay', 'Nigeria', 'Panama',
       'Israel ', 'Netherlands ', 'China', 'Taiwan', 'Thailand', 'italy',
       'Israel', 'Madagascar', 'Singapore ', 'Qatar', 'Philippines',
       'Pakistan', 'Egypt ', 'Belarus ', 'Venezuela'], dtype=object)

In [11]:
df['country'].fillna("Not specified", inplace=True)

In [12]:
df['country'] = df['country'].replace('Usa', 'USA')
df['country'] = df['country'].replace('United Kingdom ', 'United Kingdom')
df['country'] = df['country'].replace(' italy', 'Italy')
df['country'] = df['country'].replace('italy', 'Italy')
df['country'] = df['country'].replace('England', 'United Kingdom')
df['country'] = df['country'].replace('England ', 'United Kingdom')
df['country'] = df['country'].replace('Finland ', 'Finland')
df['country'] = df['country'].replace('India ', 'India')
df['country'] = df['country'].replace('Israel ', 'Israel')
df['country'] = df['country'].replace('Netherlands ', 'Netherlands')
df['country'] = df['country'].replace('Singapore ', 'Singapore')
df['country'] = df['country'].replace('Egypt ', 'Egypt')
df['country'] = df['country'].replace('Belarus ', 'Belarus')
df['country'] = df['country'].replace('Germany ', 'Germany')
df['country'] = df['country'].replace('Russia ', 'Russia')
df['country'] = df['country'].replace('South Africa ', 'South Africa')

In [13]:
df1 = df[['country', 'years', 'role', 'level', 'mode', 'value']]
df1.to_csv('cleaned_survey_results_filtered.csv', index=False)

In [14]:
len(df1['country'].unique())

77

In [15]:
df1['country'].unique()

array(['USA', 'Tanzania', 'Greece', 'Australia', 'Vietnam', 'Spain',
       'Canada', 'Not specified', 'El Salvador', 'United Kingdom',
       'Chile', 'Sweden', 'India', 'Argentina', 'France', 'Luxembourg',
       'Germany', 'Italy', 'Peru', 'Japan', 'Mexico', 'Brazil',
       'South Africa', 'Ireland', 'Europe', 'Singapore', 'Belgium',
       'Hong Kong ', 'Malaysia', 'New Zealand', 'Russia', 'Hungary',
       'Finland', 'Turkey', 'Denmark', 'Netherlands', 'Estonia',
       'Switzerland', 'Colombia', 'Kenya', 'Tunisia', 'Kuwait',
       'Slovenia', 'Uganda', 'Dominican Republic', 'Indonesia', 'Serbia',
       'Scotland', 'Hong Kong', 'Ecuador', 'Costa Rica', 'Iceland',
       'Saudi Arabia', 'Norway', 'Poland', 'Austria', 'Cuba', 'Lebanon',
       'Portugal', 'Croatia', 'Belarus', 'Georgia', 'Bermuda', 'Romania',
       'Uruguay', 'Nigeria', 'Panama', 'Israel', 'China', 'Taiwan',
       'Thailand', 'Madagascar', 'Qatar', 'Philippines', 'Pakistan',
       'Egypt', 'Venezuela'], dtype=object)

In [16]:
df1

,country,years,role,level,mode,value
0,USA,2.0,Academic,Data visualization is an important secondary p...,"Business Intelligence Tools (like Tableau), Ge...",7
1,Tanzania,6.0,"Leadership (Manager, Director, VP, etc)",Data visualization is the focus of my job,"General purpose charting libraries (plotly, hi...",7
2,USA,7.0,"Leadership (Manager, Director, VP, etc)",Data visualization is one of several other thi...,"Business Intelligence Tools (like Tableau), Co...",4
3,USA,5.0,"Leadership (Manager, Director, VP, etc)",Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),7
4,USA,5.0,"Leadership (Manager, Director, VP, etc)",Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),7
5,USA,NaN,Developer,Data visualization is one of several other thi...,"Business Intelligence Tools (like Tableau), Co...",6
6,USA,8.0,Analyst,Data visualization is an important secondary p...,"Business Intelligence Tools (like Tableau), Co...",7
7,Greece,25.0,"Leadership (Manager, Director, VP, etc)",Data visualization is one of several other thi...,"Business Intelligence Tools (like Tableau), Ge...",6
8,USA,8.0,Academic,Data visualization is an important secondary p...,"Interactive Notebooks, Completely custom (matp...",7
9,USA,4.0,"Leadership (Manager, Director, VP, etc)",Data visualization is the focus of my job,"Business Intelligence Tools (like Tableau), Co...",7
10,USA,0.0,None of these describe my role,Data visualization is one of several other thi...,Business Intelligence Tools (like Tableau),3
11,USA,15.0,"Leadership (Manager, Director, VP, etc)",Data visualization is the focus of my job,"Business Intelligence Tools (like Tableau), Ha...",7
12,USA,3.0,Student,Data visualization is the focus of my job,"Interactive Notebooks, General purpose chartin...",6
13,Australia,5.0,Academic,Data visualization is an important secondary p...,"Business Intelligence Tools (like Tableau), Co...",2
14,USA,20.0,"Leadership (Manager, Director, VP, etc)",Data visualization is an important secondary p...,"Business Intelligence Tools (like Tableau), Co...",7
15,Vietnam,1.0,Engineer,Data visualization is an important secondary p...,Powerpoint,5
16,USA,11.0,Engineer,Data visualization is an important secondary p...,"Business Intelligence Tools (like Tableau), Co...",6
17,USA,0.0,Designer,Data visualization is one of several other thi...,"Business Intelligence Tools (like Tableau), Ha...",7
18,USA,8.0,Designer,Data visualization is an important secondary p...,"Business Intelligence Tools (like Tableau), Ge...",6
19,USA,15.0,Designer,Data visualization is an important secondary p...,Hand-crafted in a graphics editor (Illustrator),5
20,Vietnam,3.0,Scientist,Data visualization is one of several other thi...,"Interactive Notebooks, Completely custom (matp...",5
21,USA,4.0,Scientist,Data visualization is one of several other thi...,"Interactive Notebooks, Completely custom (matp...",3
22,Spain,10.0,Analyst,Data visualization is the focus of my job,"Business Intelligence Tools (like Tableau), Co...",7
23,Canada,5.0,Analyst,Data visualization is an important secondary p...,"Business Intelligence Tools (like Tableau), En...",4
24,USA,10.0,Academic,Data visualization is one of several other thi...,Hand-crafted in a graphics editor (Illustrator...,6
25,Not specified,NaN,"Leadership (Manager, Director, VP, etc)",Data visualization is one of several other thi...,"Business Intelligence Tools (like Tableau), Co...",2
26,USA,7.0,Academic,Data visualization is an important secondary p...,"Interactive Notebooks, Completely custom (matp...",NaN
27,USA,2.0,None of these describe my role,Data visualization is one of several other thi...,"Business Intelligence Tools (like Tableau), In...",5
28,USA,2.0,Analyst,Data visualization is one of several other thi...,Business Intelligence Tools (like Tableau),3
29,USA,8.0,Designer,Data visualization is the focus of my job,"Business Intelligence Tools (like Tableau), Co...",6
...,...,...,...,...,...,...
1329,Canada,8.0,Designer,Data visualization is the focus of my job,Business Intelligence Tools (like Tableau),3
1330,Not specified,2.0,Analyst,Data visualization is the focus of my job,"Notebooks, General purpose charting libraries ...",No
1331,USA,3.0,Analyst,Data visualization is the focus of my job,Business Intelligence Tools (like Tableau),4
1332,Not specified,NaN,Analyst,Data visualization is one of several other thi...,NaN,NaN
1333,Not specified,NaN,Analyst,Data visualization is one of several other thi...,"Business Intelligence Tools (like Tableau), In...",NaN
1334,USA,7.0,Analyst,Data visualization is an important secondary p...,"General purpose charting libraries (plotly, hi...",5
1335,Not specified,NaN,Scientist,Data visualization is an important secondary p...,"General purpose charting libraries (plotly, hi...",6
1336,Not specified,NaN,Analyst,Data visualization is an important secondary p...,"Completely custom (matplotlib, ggplot2, Proces...",3
1337,Not specified,NaN,Analyst,Data visualization is one of several other thi...,NaN,NaN
1338,Not specified,NaN,None of these describe my role,Data visualization is one of several other thi...,Business Intelligence Tools (like Tableau),4
1339,Not specified,2.0,Engineer,Data visualization is an important secondary p...,"Business Intelligence Tools (like Tableau), In...",6
1340,USA,10.0,Scientist,Data visualization is one of several other thi...,"Business Intelligence Tools (like Tableau), In...",7
1341,USA,10.0,"Leadership (Manager, Director, VP, etc)",Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),6
1342,Argentina,12.0,Scientist,Data visualization is an important secondary p...,"Business Intelligence Tools (like Tableau), Ge...",4
1343,Not specified,NaN,Engineer,Data visualization is an important secondary p...,"Business Intelligence Tools (like Tableau), In...",6
1344,Brazil,1.0,Scientist,Data visualization is one of several other thi...,"General purpose charting libraries (plotly, hi...",3
1345,Not specified,NaN,Designer,Data visualization is one of several other thi...,"General purpose charting libraries (plotly, hi...",7
1346,Not specified,NaN,Student,NaN,NaN,NaN
1347,Not specified,NaN,Engineer,Data visualization is one of several other thi...,"Business Intelligence Tools (like Tableau), Ge...",1
1348,Not specified,0.0,Academic,Data visualization is an important secondary p...,Excel,6
1349,Not specified,NaN,Analyst,Data visualization is an important secondary p...,"Business Intelligence Tools (like Tableau), Co...",6
1350,USA,NaN,Student,Data visualization is an important secondary p...,"Business Intelligence Tools (like Tableau), In...",NaN
1351,Not specified,NaN,Engineer,Data visualization is the focus of my job,NaN,NaN
1352,Not specified,NaN,Analyst,Data visualization is one of several other thi...,Business Intelligence Tools (like Tableau),4
1353,Scotland,7.0,Developer,Data visualization is the focus of my job,"Business Intelligence Tools (like Tableau), In...",7
1354,Mexico,2.0,Student,Data visualization is the focus of my job,"Interactive Notebooks, General purpose chartin...",2
1355,Not specified,8.0,Academic,Data visualization is one of several other thi...,Hand-crafted in a graphics editor (Illustrator),4
1356,USA,4.0,"Leadership (Manager, Director, VP, etc)",Data visualization is the focus of my job,Business Intelligence Tools (like Tableau),2
1357,Finland,5.0,Student,NaN,"Business Intelligence Tools (like Tableau), Co...",NaN
1358,Not specified,NaN,Engineer,Data visualization is one of several other thi...,"Business Intelligence Tools (like Tableau), In...",NaN

In [17]:
def multireplace(string, replacements):
    """
    Given a string and a replacement map, it returns the replaced string.
    :param str string: string to execute replacements on
    :param dict replacements: replacement dictionary {value to find: value to replace}
    :rtype: str
    """
    # Place longer ones first to keep shorter substrings from matching where the longer ones should take place
    # For instance given the replacements {'ab': 'AB', 'abc': 'ABC'} against the string 'hey abc', it should produce
    # 'hey ABC' and not 'hey ABc'
    substrs = sorted(replacements, key=len, reverse=True)
    
    # Create a big OR regex that matches any of the substrings to replace
    regexp = re.compile('|'.join(map(re.escape, substrs)))

    # For each match, look up the new string in the replacements
    return regexp.sub(lambda match: replacements[match.group(0)], string)

In [18]:
df1["mode"] = df1["mode"].apply(lambda x: multireplace(str(x), {'Processing': 'processing', 'D3': 'd3', 'Excel': 'excel'}))

/Users/dianaow/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [19]:
test = df1["mode"].str.split(r'\s*,\s*(?=[A-Z])', expand=True)

In [106]:
arr = ['Business Intelligence Tools (like Tableau)', 'Interactive Notebooks', \
       'General purpose charting libraries (plotly, highcharts)',\
        'Hand-crafted in a graphics editor (Illustrator)',\
        'Hand-crafted with pen & paper or other physical means',\
        'Completely custom (matplotlib, ggplot2, processing, d3, custom code)']
arr.insert(0,'country')
arr.insert(0,'role')
arr.insert(0,'level')

In [107]:
for i,row in test.iterrows():
    if 'Business Intelligence Tools (like Tableau)' in row.values:
        test.loc[i, 'Business Intelligence Tools (like Tableau)'] = 1
    if 'General purpose charting libraries (plotly, highcharts)' in row.values:
        test.loc[i, 'General purpose charting libraries (plotly, highcharts)'] = 1
    if 'Interactive Notebooks' in row.values:
        test.loc[i, 'Interactive Notebooks'] = 1
    if 'Hand-crafted in a graphics editor (Illustrator)' in row.values:
        test.loc[i, 'Hand-crafted in a graphics editor (Illustrator)'] = 1
    if 'Hand-crafted with pen & paper or other physical means' in row.values:
        test.loc[i, 'Hand-crafted with pen & paper or other physical means'] = 1
    if 'Completely custom (matplotlib, ggplot2, processing, d3, custom code)' in row.values:
        test.loc[i, 'Completely custom (matplotlib, ggplot2, processing, d3, custom code)'] = 1
    #for el in row.values:
        #if 'excel' or 'Excel' in el:
            #test.loc[i, 'Excel'] = 1

In [108]:
df2 = pd.concat([df1, test], axis=1)
df2 = df2[arr].fillna(0)
df2=pd.melt(df2,id_vars=['country', 'role', 'level'], var_name=['mode'], value_name='values')
#df2.to_csv('grouped_modes.csv', index=False)

In [109]:
df2

,country,role,level,mode,values
0,USA,Academic,Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),1.0
1,Tanzania,"Leadership (Manager, Director, VP, etc)",Data visualization is the focus of my job,Business Intelligence Tools (like Tableau),0.0
2,USA,"Leadership (Manager, Director, VP, etc)",Data visualization is one of several other thi...,Business Intelligence Tools (like Tableau),1.0
3,USA,"Leadership (Manager, Director, VP, etc)",Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),1.0
4,USA,"Leadership (Manager, Director, VP, etc)",Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),1.0
5,USA,Developer,Data visualization is one of several other thi...,Business Intelligence Tools (like Tableau),1.0
6,USA,Analyst,Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),1.0
7,Greece,"Leadership (Manager, Director, VP, etc)",Data visualization is one of several other thi...,Business Intelligence Tools (like Tableau),1.0
8,USA,Academic,Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),0.0
9,USA,"Leadership (Manager, Director, VP, etc)",Data visualization is the focus of my job,Business Intelligence Tools (like Tableau),1.0
10,USA,None of these describe my role,Data visualization is one of several other thi...,Business Intelligence Tools (like Tableau),1.0
11,USA,"Leadership (Manager, Director, VP, etc)",Data visualization is the focus of my job,Business Intelligence Tools (like Tableau),1.0
12,USA,Student,Data visualization is the focus of my job,Business Intelligence Tools (like Tableau),0.0
13,Australia,Academic,Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),1.0
14,USA,"Leadership (Manager, Director, VP, etc)",Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),1.0
15,Vietnam,Engineer,Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),0.0
16,USA,Engineer,Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),1.0
17,USA,Designer,Data visualization is one of several other thi...,Business Intelligence Tools (like Tableau),1.0
18,USA,Designer,Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),1.0
19,USA,Designer,Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),0.0
20,Vietnam,Scientist,Data visualization is one of several other thi...,Business Intelligence Tools (like Tableau),0.0
21,USA,Scientist,Data visualization is one of several other thi...,Business Intelligence Tools (like Tableau),0.0
22,Spain,Analyst,Data visualization is the focus of my job,Business Intelligence Tools (like Tableau),1.0
23,Canada,Analyst,Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),1.0
24,USA,Academic,Data visualization is one of several other thi...,Business Intelligence Tools (like Tableau),0.0
25,Not specified,"Leadership (Manager, Director, VP, etc)",Data visualization is one of several other thi...,Business Intelligence Tools (like Tableau),1.0
26,USA,Academic,Data visualization is an important secondary p...,Business Intelligence Tools (like Tableau),0.0
27,USA,None of these describe my role,Data visualization is one of several other thi...,Business Intelligence Tools (like Tableau),1.0
28,USA,Analyst,Data visualization is one of several other thi...,Business Intelligence Tools (like Tableau),1.0
29,USA,Designer,Data visualization is the focus of my job,Business Intelligence Tools (like Tableau),1.0
...,...,...,...,...,...
8124,Canada,Designer,Data visualization is the focus of my job,"Completely custom (matplotlib, ggplot2, proces...",0.0
8125,Not specified,Analyst,Data visualization is the focus of my job,"Completely custom (matplotlib, ggplot2, proces...",0.0
8126,USA,Analyst,Data visualization is the focus of my job,"Completely custom (matplotlib, ggplot2, proces...",0.0
8127,Not specified,Analyst,Data visualization is one of several other thi...,"Completely custom (matplotlib, ggplot2, proces...",0.0
8128,Not specified,Analyst,Data visualization is one of several other thi...,"Completely custom (matplotlib, ggplot2, proces...",0.0
8129,USA,Analyst,Data visualization is an important secondary p...,"Completely custom (matplotlib, ggplot2, proces...",0.0
8130,Not specified,Scientist,Data visualization is an important secondary p...,"Completely custom (matplotlib, ggplot2, proces...",1.0
8131,Not specified,Analyst,Data visualization is an important secondary p...,"Completely custom (matplotlib, ggplot2, proces...",1.0
8132,Not specified,Analyst,Data visualization is one of several other thi...,"Completely custom (matplotlib, ggplot2, proces...",0.0
8133,Not specified,None of these describe my role,Data visualization is one of several other thi...,"Completely custom (matplotlib, ggplot2, proces...",0.0
8134,Not specified,Engineer,Data visualization is an important secondary p...,"Completely custom (matplotlib, ggplot2, proces...",0.0
8135,USA,Scientist,Data visualization is one of several other thi...,"Completely custom (matplotlib, ggplot2, proces...",1.0
8136,USA,"Leadership (Manager, Director, VP, etc)",Data visualization is an important secondary p...,"Completely custom (matplotlib, ggplot2, proces...",0.0
8137,Argentina,Scientist,Data visualization is an important secondary p...,"Completely custom (matplotlib, ggplot2, proces...",1.0
8138,Not specified,Engineer,Data visualization is an important secondary p...,"Completely custom (matplotlib, ggplot2, proces...",1.0
8139,Brazil,Scientist,Data visualization is one of several other thi...,"Completely custom (matplotlib, ggplot2, proces...",1.0
8140,Not specified,Designer,Data visualization is one of several other thi...,"Completely custom (matplotlib, ggplot2, proces...",0.0
8141,Not specified,Student,0,"Completely custom (matplotlib, ggplot2, proces...",0.0
8142,Not specified,Engineer,Data visualization is one of several other thi...,"Completely custom (matplotlib, ggplot2, proces...",0.0
8143,Not specified,Academic,Data visualization is an important secondary p...,"Completely custom (matplotlib, ggplot2, proces...",0.0
8144,Not specified,Analyst,Data visualization is an important secondary p...,"Completely custom (matplotlib, ggplot2, proces...",1.0
8145,USA,Student,Data visualization is an important secondary p...,"Completely custom (matplotlib, ggplot2, proces...",1.0
8146,Not specified,Engineer,Data visualization is the focus of my job,"Completely custom (matplotlib, ggplot2, proces...",0.0
8147,Not specified,Analyst,Data visualization is one of several other thi...,"Completely custom (matplotlib, ggplot2, proces...",0.0
8148,Scotland,Developer,Data visualization is the focus of my job,"Completely custom (matplotlib, ggplot2, proces...",1.0
8149,Mexico,Student,Data visualization is the focus of my job,"Completely custom (matplotlib, ggplot2, proces...",1.0
8150,Not specified,Academic,Data visualization is one of several other thi...,"Completely custom (matplotlib, ggplot2, proces...",0.0
8151,USA,"Leadership (Manager, Director, VP, etc)",Data visualization is the focus of my job,"Completely custom (matplotlib, ggplot2, proces...",0.0
8152,Finland,Student,0,"Completely custom (matplotlib, ggplot2, proces...",1.0
8153,Not specified,Engineer,Data visualization is one of several other thi...,"Completely custom (matplotlib, ggplot2, proces...",0.0

In [105]:
df4pd.DataFrame(df.groupby(['role', 'level'])['index'].count()).reset_index()
df4.to_csv('grouped_modes.csv', index=False)

NameError: name 'df4pd' is not defined

In [23]:
df['years'] = df['years'].replace(0.1, 0)
df['years'] = df['years'].replace(0.166, 0)
df['years'] = df['years'].replace(0.3, 0.5)
df['years'] = df['years'].replace(0.4, 0.5)

In [24]:
grouped = pd.DataFrame(df.groupby(['country', 'years'])['index'].count()).reset_index()

In [25]:
grouped_pt = pd.pivot_table(grouped, values='index', index='country', columns='years', fill_value=0).reset_index()

In [26]:
grouped_melt = pd.melt(grouped_pt, id_vars=['country']).sort_values(['country', 'years'], ascending=True)

In [27]:
grouped_melt['date'] = grouped_melt['years'].apply(lambda x: (datetime.datetime(2019, 1, 1) - datetime.timedelta(x*365)) if x>= 2 else (datetime.datetime(2019, 6, 15) - datetime.timedelta(x*365)))

In [28]:
grouped_melt['date_year'] = grouped_melt['date'].apply(lambda x: datetime.datetime.strftime(x, "%Y"))

In [29]:
grouped_melt['date'] = grouped_melt['date'].apply(lambda x: datetime.datetime.strftime(x, "%b %Y"))

In [30]:
grouped_melt['datetime'] = grouped_melt['date'].apply(lambda x: datetime.datetime.strptime(x, "%b %Y"))

In [31]:
grouped_melt = grouped_melt.sort_values(['country', 'datetime'], ascending=True)

In [32]:
grouped_cumsum = grouped_melt.groupby(['country', 'datetime']).sum().groupby('country').cumsum().reset_index()

In [33]:
grouped_cumsum['date'] = grouped_cumsum['datetime'].apply(lambda x: datetime.datetime.strftime(x, "%b %Y"))

In [34]:
grouped_cumsum[grouped_cumsum['country'] == 'India']

     country   datetime  value      date
1020   India 1979-01-01      0  Jan 1979
1021   India 1984-01-01      0  Jan 1984
1022   India 1989-01-01      0  Jan 1989
1023   India 1990-01-01      0  Jan 1990
1024   India 1991-01-01      0  Jan 1991
1025   India 1992-01-01      0  Jan 1992
1026   India 1994-01-01      0  Jan 1994
1027   India 1995-01-01      0  Jan 1995
1028   India 1999-01-01      0  Jan 1999
1029   India 2000-01-01      0  Jan 2000
1030   India 2001-01-01      0  Jan 2001
1031   India 2002-01-01      0  Jan 2002
1032   India 2003-01-01      0  Jan 2003
1033   India 2004-01-01      0  Jan 2004
1034   India 2005-01-01      0  Jan 2005
1035   India 2006-01-01      1  Jan 2006
1036   India 2007-01-01      2  Jan 2007
1037   India 2008-01-01      2  Jan 2008
1038   India 2009-01-01      5  Jan 2009
1039   India 2010-01-01      6  Jan 2010
1040   India 2011-01-01      6  Jan 2011
1041   India 2011-07-01      6  Jul 2011
1042   India 2012-01-01      8  Jan 2012
1043   India 2012-07-01      8  Jul 2012
1044   India 2013-01-01      8  Jan 2013
1045   India 2014-01-01     16  Jan 2014
1046   India 2015-01-01     19  Jan 2015
1047   India 2016-01-01     23  Jan 2016
1048   India 2016-07-01     24  Jul 2016
1049   India 2017-01-01     28  Jan 2017
1050   India 2017-12-01     28  Dec 2017
1051   India 2018-06-01     36  Jun 2018
1052   India 2018-12-01     38  Dec 2018
1053   India 2019-06-01     39  Jun 2019

In [35]:
grouped_cumsum.to_csv('grouped_melt.csv', index=False)